### ISSUE TITLE
Base Model

### ISSUE THREAD

**Issue by andupotorac** [jitcoder/lora-info#14]
Do we have to write that ourselves for the Lora we selected? If not, why isn't it going out like trigger_words and example_prompt?

**Comment by jitcoder** [comment]
its been a while since i worked on this, but base model is a displayed field that populates after you select it. its purpose is informative. the fields that get outputted are fields that are "actionable". eg. populating a prompt automatically with trigger words, or using the example prompt itself directly etc. The base model text isn't output in this case since its not directly actionable as far as I know but obviously I could be wrong. If you have a use case where you would use the output of what the base model is I'd be more than happy to consider a PR

**Comment by andupotorac** [comment]
Oh, got it. This makes sense!
